import type { ActivityEvent, AppNotification, CalendarEvent } from "./types";

export const activityLog: ActivityEvent[] = [
  {
    id: "act-001",
    type: "ai_scan_run",
    caseId: "case-001",
    patientName: "Elena Vasquez",
    performedBy: "Dr. Maya Laurent",
    timestamp: "2026-07-09T09:14:00Z",
    detail: "AI risk score: 82 — High priority flag raised",
  },
  {
    id: "act-002",
    type: "case_opened",
    caseId: "case-003",
    patientName: "Sarah Chen",
    performedBy: "Dr. Maya Laurent",
    timestamp: "2026-07-09T09:02:00Z",
    detail: "Opened new patient intake from queue",
  },
  {
    id: "act-003",
    type: "case_approved",
    caseId: "case-007",
    patientName: "Lisa Bergström",
    performedBy: "Dr. Maya Laurent",
    timestamp: "2026-07-09T08:51:00Z",
    detail: "Benign nevus — cleared for annual monitoring",
  },
  {
    id: "act-004",
    type: "doctor_note_added",
    caseId: "case-002",
    patientName: "James Okonkwo",
    performedBy: "Dr. Maya Laurent",
    timestamp: "2026-07-09T08:40:00Z",
    detail: "Updated intake notes with patient-reported history",
  },
  {
    id: "act-005",
    type: "report_generated",
    caseId: "case-007",
    patientName: "Lisa Bergström",
    performedBy: "Dr. Maya Laurent",
    timestamp: "2026-07-09T08:49:00Z",
    detail: "PDF report exported for patient record",
  },
  {
    id: "act-006",
    type: "new_scan_requested",
    caseId: "case-009",
    patientName: "Priya Sharma",
    performedBy: "Dr. Maya Laurent",
    timestamp: "2026-07-08T16:33:00Z",
    detail: "Image quality below threshold — re-scan requested",
  },
  {
    id: "act-007",
    type: "case_created",
    caseId: "case-009",
    patientName: "Priya Sharma",
    performedBy: "Dr. Maya Laurent",
    timestamp: "2026-07-08T16:30:00Z",
    detail: "New patient case registered via intake form",
  },
  {
    id: "act-008",
    type: "ai_scan_run",
    caseId: "case-002",
    patientName: "James Okonkwo",
    performedBy: "Dr. Maya Laurent",
    timestamp: "2026-07-08T14:22:00Z",
    detail: "AI risk score: 76 — Follow-up recommended within 4 weeks",
  },
  {
    id: "act-009",
    type: "case_opened",
    caseId: "case-006",
    patientName: "Robert Kim",
    performedBy: "Dr. Maya Laurent",
    timestamp: "2026-07-08T11:05:00Z",
    detail: "Reviewed scalp lesion case",
  },
  {
    id: "act-010",
    type: "ai_scan_run",
    caseId: "case-004",
    patientName: "Michael Torres",
    performedBy: "Dr. Maya Laurent",
    timestamp: "2026-07-07T15:47:00Z",
    detail: "AI risk score: 48 — Medium priority, standard queue",
  },
  {
    id: "act-011",
    type: "case_approved",
    caseId: "case-010",
    patientName: "Thomas Wright",
    performedBy: "Dr. Maya Laurent",
    timestamp: "2026-07-07T13:10:00Z",
    detail: "Annual follow-up sign-off completed",
  },
  {
    id: "act-012",
    type: "doctor_note_added",
    caseId: "case-005",
    patientName: "Amara Diallo",
    performedBy: "Dr. Maya Laurent",
    timestamp: "2026-07-06T10:18:00Z",
    detail: "Patient requests continued monitoring over removal",
  },
];

export const notifications: AppNotification[] = [
  {
    id: "notif-001",
    level: "high",
    title: "High-risk case requires immediate review",
    body: "Elena Vasquez — AI risk score 82. Border irregularity exceeds clinic threshold.",
    caseId: "case-001",
    patientName: "Elena Vasquez",
    timestamp: "2026-07-09T09:14:00Z",
    read: false,
  },
  {
    id: "notif-002",
    level: "reminder",
    title: "Follow-up due today",
    body: "James Okonkwo is scheduled for a 4-week follow-up check today.",
    caseId: "case-002",
    patientName: "James Okonkwo",
    timestamp: "2026-07-09T08:00:00Z",
    read: false,
  },
  {
    id: "notif-003",
    level: "info",
    title: "AI review completed",
    body: "Sarah Chen — ABCDE analysis ready. Awaiting clinician verification.",
    caseId: "case-003",
    patientName: "Sarah Chen",
    timestamp: "2026-07-09T09:02:00Z",
    read: false,
  },
  {
    id: "notif-004",
    level: "reminder",
    title: "Re-scan pending — image quality flag",
    body: "Priya Sharma's case is awaiting a new dermoscopic photo before AI review can continue.",
    caseId: "case-009",
    patientName: "Priya Sharma",
    timestamp: "2026-07-08T16:33:00Z",
    read: true,
  },
  {
    id: "notif-005",
    level: "high",
    title: "High-risk case added to queue",
    body: "James Okonkwo — AI score 76. Variegated pigmentation and border irregularity detected.",
    caseId: "case-002",
    patientName: "James Okonkwo",
    timestamp: "2026-07-08T14:22:00Z",
    read: true,
  },
  {
    id: "notif-006",
    level: "info",
    title: "Case approved and cleared",
    body: "Lisa Bergström — Benign nevus confirmed. Annual monitoring scheduled.",
    caseId: "case-007",
    patientName: "Lisa Bergström",
    timestamp: "2026-07-09T08:51:00Z",
    read: true,
  },
  {
    id: "notif-007",
    level: "reminder",
    title: "Follow-up due today",
    body: "Thomas Wright's 6-month check-in is scheduled for today.",
    caseId: "case-010",
    patientName: "Thomas Wright",
    timestamp: "2026-07-09T08:00:00Z",
    read: true,
  },
  {
    id: "notif-008",
    level: "info",
    title: "New case registered",
    body: "Priya Sharma added via patient intake form. AI review pending.",
    caseId: "case-009",
    patientName: "Priya Sharma",
    timestamp: "2026-07-08T16:30:00Z",
    read: true,
  },
];

export const calendarEvents: CalendarEvent[] = [
  {
    id: "cal-001",
    caseId: "case-002",
    patientName: "James Okonkwo",
    priority: "high",
    date: "2026-07-09",
    time: "10:30",
    durationMin: 30,
    type: "follow_up",
    lesionLocation: "Right shoulder",
    mrn: "MRN-31904",
  },
  {
    id: "cal-002",
    caseId: "case-010",
    patientName: "Thomas Wright",
    priority: "low",
    date: "2026-07-09",
    time: "14:00",
    durationMin: 30,
    type: "follow_up",
    lesionLocation: "Right thigh",
    mrn: "MRN-11356",
  },
  {
    id: "cal-002b",
    caseId: "case-004",
    patientName: "Michael Torres",
    priority: "medium",
    date: "2026-07-09",
    time: "16:30",
    durationMin: 30,
    type: "follow_up",
    lesionLocation: "Chest",
    mrn: "MRN-55182",
  },
  {
    id: "cal-003",
    caseId: "case-009",
    patientName: "Priya Sharma",
    priority: "medium",
    date: "2026-07-11",
    time: "09:00",
    durationMin: 45,
    type: "new_scan_requested",
    lesionLocation: "Left shoulder",
    mrn: "MRN-10245",
  },
  {
    id: "cal-004",
    caseId: "case-005",
    patientName: "Amara Diallo",
    priority: "medium",
    date: "2026-07-14",
    time: "11:15",
    durationMin: 30,
    type: "follow_up",
    lesionLocation: "Left thigh",
    mrn: "MRN-66703",
  },
  {
    id: "cal-005",
    caseId: "case-001",
    patientName: "Elena Vasquez",
    priority: "high",
    date: "2026-07-15",
    time: "08:30",
    durationMin: 45,
    type: "follow_up",
    lesionLocation: "Left forearm",
    mrn: "MRN-28471",
  },
  {
    id: "cal-006",
    caseId: "case-006",
    patientName: "Robert Kim",
    priority: "medium",
    date: "2026-07-16",
    time: "13:00",
    durationMin: 30,
    type: "follow_up",
    lesionLocation: "Scalp",
    mrn: "MRN-77891",
  },
  {
    id: "cal-007",
    caseId: "case-004",
    patientName: "Michael Torres",
    priority: "medium",
    date: "2026-07-21",
    time: "10:00",
    durationMin: 30,
    type: "follow_up",
    lesionLocation: "Chest",
    mrn: "MRN-55182",
  },
  {
    id: "cal-008",
    caseId: "case-003",
    patientName: "Sarah Chen",
    priority: "high",
    date: "2026-07-23",
    time: "09:30",
    durationMin: 45,
    type: "follow_up",
    lesionLocation: "Upper back",
    mrn: "MRN-44210",
  },
];
